function plot_locations(locs)
%
% A function that plots the cooridinate points generated by
% locations.m on a Miller projected world map. 
%
% As in plot_map_miller.m, the grid is centered on 0 longitude.
% 
% INPUT:				locs		, cooridinate pairs [longitude,latitude]
%														generated by ~/proj/etienne/locations.m
% ====================================================================

	close;
	name = 'locs';			% name for output figure

	% Load m_map (for better plotting)
	addpath('/home/disk/p/etienne/proj/m_map/')
	
	
	FIG = figure('visible','off');		% no term X figure

	x = locs(:,1);						% longitude coordinate
	y = locs(:,2);						% latitude
	Nlocs = length(x);				% how many locations

	% Shift the grid to [-180:180] if needed
	for i=1:Nlocs
		if (x(i) > 180);  x(i) = x(i) - 360; end
	end

	%% Using the m_map set of procedures (~/proj/m_map/)

	% -) select projection type  (same as in plot_map_miller.m)
	m_proj('miller','lat',[-55,77],'lon',[1.25-180,358.75-180]);		
		
	% -) remove grid, thicker box
	m_grid('xtick',[],'ytick',[],'linewidth',1.2); hold on
		
	% -) plot data (without contour lines)
	m_text(x,y,'.','color','b','fontweight','bold','fontsize',20);
		
	% -) add annotations
	for i=1:Nlocs
		
		tmp_text = num2str(i);
		tmpx = x(i)+1.5;
		tmpy = y(i)+1;					% top right corner of grid point

		m_text(tmpx,tmpy,tmp_text,'color','k');

	end

	% -) draw coast lines 
	m_coast('color',[0 0 0],'linewidth',0.75);
		
	% -) select output figure size
	set(gcf,'paperunits','centimeter','paperposition',[0,0,20,10]);
		
	% printing ouptut using plot_print.m
	plot_print; close(FIG);

end
