%%% Program that plots the timeseries of the anomalies fields
	% for all the locations generated by locations.m
	%
	% Using plot_ts, the anomalies XX will be acompagnied by
	% their standard deviations +/- sig_X.
% ======================================================================

% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
	

%% Plotting timeseries of all anomalies by first looping though $vars
 % and then looping through the locations (inside plot_ts_locs.m)

for i=1:Nvar				% looping though $vars
		
		% allocating Z and sig_Z for $vars(i) --- refer to plot_ts_locs.m
	eval(['Z = ' char(vars(i)) char(vars(i)) ';']);
	eval(['sig_Z = sig_' char(vars(i)) ';']);
	
		% selecting $tsvals, $cols and $yvals for $vars(i)
		% convert to mm/day for E, P, R and R(b).		TO DO !!!
	switch i

		case 1;		% TT
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
		case 2;		% mm
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
		case 3;		% mbmb
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
		case 4;		% FF
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
		case 5;		% PP
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
			Z = Z*secinday;	sig_Z = sig_Z*secinday;				% mm/day
		case 6;		% EE
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
			Z = Z*secinday;	sig_Z = sig_Z*secinday;				% mm/day
		case 7;		% HH
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
		case 8;		% RR
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
			Z = Z*secinday;	sig_Z = sig_Z*secinday;				% mm/day
		case 9;		% RbRb
			tsvals = [-4,4]; cols = 'b'; yvals = 0.6;
			Z = Z*secinday;	sig_Z = sig_Z*secinday;				% mm/day

	end

		% name for output for $vars(i)
	name = [char(vars(i)) char(vars(i))];

		% not plotting Zbar --- refer to plot_ts_locs.m
	Zbar = [];

		%% plot timeseries using ---> plot_ts_locs.m
	plot_ts_locs;

end
% ======================================================================
