% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% comp_tm_corrs.m
%
% --> plot_comp_datasets.m <--
%
% Cross-datasets comparison toy model correlation patterns
%
% Do corr(T',P'), corr(T',F') and corr(T',F_0') with T' of the toy
% model correspond their T' analogs?
%
% ======================================================================

%name_add = 'alt';
name_add = '';
out_format = 'both';
opt_overlay = 0;
opt_frame_col = 0;

cvec = [-1:0.2:1];
color_handle = @color_corr;
opt_x_cvec = [];
units = '[-]';

opt_tilde = 1;
%vars_req = {'lon','lat', ...
%            'cor_TE','cor_TE_tilde','check_cor_TE', ...
%            'cor_tmbias','cor_tmbias_tilde'};
vars_req = {'lon','lat', ...
            'cor_TP','cor_TP_tilde','check_cor_TP'};

%comp_cmd = [ ...
%  'gamma = [];' ...
%  'beta = [];' ...
%  'tm_param_full;' ...
%  '[j1,cor_TE] = corr_inst(tm_TT,EE,[],[]);' ...
%  '[j1,cor_TE_tilde] = corr_inst(tm_TT_tilde,EE,[],[]);' ...
%  '[j1,check_cor_TE] = corr_inst(TT,EE,[],[]);' ...
%  '[j1,cor_tmbias] = corr_inst(tm_TT-TT,TT,[],[]);' ...
%  '[j1,cor_tmbias_tilde] = corr_inst(tm_TT_tilde-TT,TT,[],[]);' ...
%  ];
comp_cmd = [ ...
  'gamma = [];' ...
  'beta = [];' ...
  'tm_param_full;' ...
  '[j1,cor_TP] = corr_inst(tm_TT,PP,[],[]);' ...
  '[j1,cor_TP_tilde] = corr_inst(tm_TT_tilde,PP,[],[]);' ...
  '[j1,check_cor_TP] = corr_inst(TT,PP,[],[]);' ...
  ];
% ----------------------------------------------------------------------

%% Call plot_comp_datasets.m

%plot_comp_datasets;
% ----------------------------------------------------------------------

%% ccsm3 product of cor_TP and check_cor_TP

name = 'ccsm3_cor_TP_sign_check';
Z = ccsm3_cor_TP.*ccsm3_check_cor_TP;
cvec = [-1,0,1];
opt_x_cvec = 'none';
color_handle = @color_sign;
plot_map_miller2( ...
  ccsm3_lon,ccsm3_lat,Z, ...
  cvec,opt_x_cvec,name,color_handle,units);
plot_map_miller2( ...
  ccsm3_lon,ccsm3_lat,Z, ...
  cvec,opt_x_cvec,[name,'.eps'],color_handle,units);
% ----------------------------------------------------------------------
