% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
%$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% comp_tm_bld.m
%
% --> plot_comp_datasets.m <--
%
% Toy model calibration errors, on Var(T) and Var(m) 
% after each 'building' parameterizations.
%
% Also, errors on Var(T) when setting m'=0 i.e. the net 
% effect on soil moisture anomalies.
%
% ======================================================================

%name_add = 'tmp';
clear name_add
clear case_cmd
out_format = 'both';
opt_frame_col = 0;
opt_overlay = 2;      % for 'tm_T_no_m'
units = '[-]';

cvec = [0,0.25,0.5,0.8,0.9,1,1.1,1.25,2,4];   
opt_x_cvec = 'above';
color_handle = @color_relerror;
%bins = [0,5];
%yval = 5;

vars_req = {'lon','lat', ...
            'tm_T_no_E00','tm_T_no_Hs00', ...
            'tm_T_no_Flu0','tm_T_no_xiU0', ...
            'tm_T_no_m', ...
            'tm_m_no_E00','tm_m_no_R0','tm_m_no_xim00'};

vars_req = {'lon','lat', ...
            'tm_T_no_E00','tm_T_no_Hs00'};

% computation commands

cmd_no_E00 = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(nu_E).*mm+xmonth(lambda/L).*FF)' ...
'- xmonth(-L*nu_Hs).*mm' ...
'- Hs00Hs00 - xiU0xiU0 - Flu0Flu0);' ...
];

cmd_no_Hs00 = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(nu_E).*mm+xmonth(lambda/L).*FF)' ...
'- xmonth(-L*nu_Hs).*mm' ...
'- L*E00E00 - xiU0xiU0 - Flu0Flu0);' ...
];

cmd_no_xiU0 = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(nu_E).*mm+xmonth(lambda/L).*FF)' ...
'- xmonth(-L*nu_Hs).*mm' ...
'- L*E00E00 - Hs00Hs00 - Flu0Flu0);' ...
];

cmd_no_Flu0 = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(nu_E).*mm+xmonth(lambda/L).*FF)' ...
'- xmonth(-L*nu_Hs).*mm' ...
'- L*E00E00 - Hs00Hs00 - xiU0xiU0);' ...
];

cmd_no_m = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(lambda/L).*FF)' ...
'- L*E00E00 - Hs00Hs00 - Flu0Flu0 - xiU0xiU0);' ...
];

cmd_m_no_E00 = [ ...
'y = xmonth(1./nu_s).*(PP' ...
'- (xmonth(lambda/L).*FF)' ...
'- xmonth(beta_R).*PP - xmonth(beta_I).*PP' ...
'- R0R0 - xim00xim00);' ...
];

cmd_m_no_R0 = [ ...
'y = xmonth(1./nu_s).*(PP' ...
'- (xmonth(lambda/L).*FF)' ...
'- xmonth(beta_R).*PP - xmonth(beta_I).*PP' ...
'- E00E00 - xim00xim00);' ...
];

cmd_m_no_xim00 = [ ...
'y = xmonth(1./nu_s).*(PP' ...
'- (xmonth(lambda/L).*FF)' ...
'- xmonth(beta_R).*PP - xmonth(beta_I).*PP' ...
'- E00E00 - R0R0);' ...
];

% full 'comp_cmd'
comp_cmd = [ ...
  'gamma = [];' ...
  'beta = [];' ...
  'alpha = [];' ...
  'tm_param_full;' ...
  ,cmd_no_E00, ...
  'tm_T_no_E00 = sqmean(anomaly_Var(x)./Var_T);' ...
  ,cmd_no_Hs00, ...
  'tm_T_no_Hs00 = sqmean(anomaly_Var(x)./Var_T);' ...
  ,cmd_no_xiU0, ...
  'tm_T_no_xiU0 = sqmean(anomaly_Var(x)./Var_T);' ...
  ,cmd_no_Flu0, ...
  'tm_T_no_Flu0 = sqmean(anomaly_Var(x)./Var_T);' ...
  ,cmd_no_m, ...
  'tm_T_no_m = sqmean(anomaly_Var(x)./Var_T);' ...
  ,cmd_m_no_E00, ...
  'tm_m_no_E00 = sqmean(anomaly_Var(y)./Var_m);' ...
  ,cmd_m_no_R0, ...
  'tm_m_no_R0 = sqmean(anomaly_Var(y)./Var_m);' ...
  ,cmd_m_no_xim00, ...
  'tm_m_no_xim00 = sqmean(anomaly_Var(y)./Var_m);' ...
  ];

% add 'opt_overlay=2' for 'tm_T_no_m'
case_cmd = [ ...
  'case {5}; opt_overlay=2;' ...
  'otherwise; opt_overlay=0;' ...
];

% ----------------------------------------------------------------------

%% Call plot_comp_datasets.m
plot_comp_datasets;
% ----------------------------------------------------------------------

break

%% Verification of T'

x = ...
  xmonth(1./gamma).*( ...
  FF ...
  - L*(xmonth(nu_E).*mm+xmonth(lambda/L).*F0F0-xmonth(lambda_P).*PP) ...
  - xmonth(-L*nu_Hs).*mm ...
  - L*E00E00 - Hs00Hs00 - xiU0xiU0 - Flu0Flu0 );

mystats(TT-x);
isthesame(TT,x)
% ----------------------------------------------------------------------

break

%% Verification of the residuals:

tm_param_full;

x = xmonth(nu_E).*mm ...
    + xmonth(lambda/L).*F0F0 ...
    - xmonth(lambda_P).*PP;
mystats(x+E00E00-EE,'E');
isthesame(x+E00E00,EE)

x = xmonth(gamma_Hs).*TT ...
    - xmonth(L*nu_Hs).*mm;
mystats(x+Hs00Hs00-HsHs,'Hs');
isthesame(x+Hs00Hs00,HsHs)

x = xmonth(gamma_lw).*TT;
mystats(x+Flu0Flu0-FluFlu,'Flu');
isthesame(x+Flu0Flu0,FluFlu)

x = xmonth(gamma_G).*TT;
mystats(x+xiU0xiU0-xiUxiU,'xiU');
isthesame(x+xiU0xiU0,xiUxiU)

x = xmonth(beta_R).*PP;
mystats(x+R0R0-RR,'R');
isthesame(x+R0R0,RR)

x = xmonth(nu_I).*mm ...
    + xmonth(beta_I).*PP;
mystats(x+xim00xim00-ximxim,'xim');
isthesame(x+xim00xim00,ximxim)
% ----------------------------------------------------------------------
