% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% comp_albedo.m
%
% --> plot_comp_datasets.m <--
%
% Albedo fluctuation scaling inside the radiation forcing term.
%
% ======================================================================

clear name_add 
%name_add = 'test';
out_format = 'both';
opt_frame_col = 0;
opt_overlay = 0;
units = '[-]';



vars_req = {'lon','lat', ...
            'scale_albedo_anom','scale_albedo_mean', ...
            'ratio_albedo_anom','ratio_albedo_mean'};

comp_cmd = [ ...
  '[Fsd,Fsdbar,FsdFsd,j3] = getnewvar(''rsds'');' ...
  '[Fsu,Fsubar,FsuFsu,j3] = getnewvar(''rsus'');' ...
  '[Fld,Fldbar,FldFld,j3] = getnewvar(''rlds'');' ...
  'A = Fsu./Fsd;' ...
  '[Abar,AA,j1] = anomaly(A);' ...
  'num = anomaly_Var( FsdFsd.*xmonth(1-Abar) + FldFld );' ...
  'den = makenan(anomaly_Var(FF),''==0'');' ...
  'scale_albedo_anom = abs(1-num./den);' ...
  'ratio_albedo_anom = num./den;' ...
  'num = Fsdbar.*(1-Abar) + Fldbar;' ...
  'den = makenan(Fbar,''==0'');' ...
  'scale_albedo_mean = abs(1-num./den);' ...
  'ratio_albedo_mean = num./den;' ...
];

%cvec = [0,0.01,0.05,0.1,0.25,0.5,1];

case_cmd = [ ...
'case 1; cvec = [0,0.001,0.01,0.1,0.25,1];' ...
  'opt_x_cvec = ''above''; color_handle = @color_small;' ...
'case 2; cvec = [0,0.0001,0.001,0.01,0.1,0.25,1];' ...
  'opt_x_cvec = ''above''; color_handle = @color_small;' ...
'case {3,4}; cvec = [0.0,0.25,0.5,0.8,0.9,1,1.1,1.25,2,4];' ...
  'opt_x_cvec = ''above''; color_handle = @color_relerror;' ...
];
% ----------------------------------------------------------------------

%% Call plot_comp_datasets.m
plot_comp_datasets;
% ----------------------------------------------------------------------
