% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% comp_scale_gammaT.m
%
% --> plot_comp_datasets.m <--
%
% Scaling of gamma^2 Var(T) / Var(F) 
%
% These results lead to the definition of the 
% land-surface 'amplified' and 'damped' regimes.
%
% (08/30): 
%
% ======================================================================

clear name_add
out_format = 'both';
opt_frame_col = 0;
units = '[-]';


f_Var_T_no_m = [ ...
'x = xmonth(1./gamma).*(FF' ...
'- L*(xmonth(lambda/L).*FF)' ...
'- L*E00E00 - Hs00Hs00 - Flu0Flu0 - xiU0xiU0);' ...
'Var_T_no_m = anomaly_Var(x);' ...
];

comp_cmd = [ ...
'gamma = [];' ...
'tm_param_full;' ...
'Var_T = sig_T.^2;' ...
'Var_F = sig_F.^2;' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
,f_Var_T_no_m, ...
'scale_gammaT_no_m = sqmean(gamma.^2.*Var_T_no_m./Var_F);' ...
'tmp = 1 - scale_gammaT_no_m./scale_gammaT;' ...
'nogood = find(tmp<-1);' ...
'tmp(nogood) = -1;' ...
'nogood = find(tmp>1);' ...
'tmp(nogood) = 1;' ...
'rel_diff_scale_gammaT = tmp;' ...
'scale_gammaT_tilde = sqmean(gamma_tilde.^2.*Var_T./Var_F);' ...
];

case_cmd = [ ...
'case {2};' ...
'cvec=[-1:0.2:1]; opt_x_cvec=''none'';' ...
'units=''[-]''; color_handle = @color_corr;' ...
'otherwise;' ...
'cvec =  [0.0,0.25,0.5,0.8,1,1.25,2,4];' ...
'opt_x_cvec = ''above'';' ...
'color_handle = @color_scale;' ...
];
% ----------------------------------------------------------------------

%% Call plot_comp_datasets.m
vars_req = {'lon','lat', ...
  'scale_gammaT','rel_diff_scale_gammaT','scale_gammaT_tilde'};
opt_tilde = 1;
%vars_req = {'lon','lat','scale_gammaT'};

%opt_overlay = 0;
opt_overlay = 2;
plot_comp_datasets;
% ----------------------------------------------------------------------

%% Call plot_compsc_datasets.m
%vars_req = {'mbar','Tbar','scale_gammaT'};
%opt_overlay = 0;
%plot_compsc_datasets;
% ----------------------------------------------------------------------
