% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% compsc_scale_engy.m
%
% --> plot_compsc_datasets.m <--
%
% # color-coded scatter plots complement of plot_scale_engy.m
%
% ======================================================================

name_add = 'engy';
out_format = 'png';
%out_format = 'eps';
opt_frame_col = 0;
opt_overlay = 0;
units = '[-]';

cvec = [-3:0.5:3];
opt_x_cvec = 'add_both';
color_handle = @color_posneg;

vars_req = {'mbar','Tbar', ...
  'scale_gammaT','scale_T_E', ...
  'scale_LE','scale_T_Hs', ...
  'scale_Hs','scale_E_Hs'};

comp_cmd = [ ...
'Var_F = sig_F.^2; Var_T = sig_T.^2;' ...
'Var_E = sig_E.^2; Var_Hs = sig_Hs.^2;' ...
'tm_param_full;' ...
'Cov_TE = cova_inst(TT,EE);' ...
'Cov_THs = cova_inst(TT,HsHs);' ...
'Cov_EHs = cova_inst(EE,HsHs);' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
'scale_LE = sqmean(L^2.*Var_E./Var_F);' ...
'scale_Hs = sqmean(Var_Hs./Var_F);' ...
'scale_T_E = sqmean(2*L*gamma.*Cov_TE./Var_F);' ...
'scale_T_Hs = sqmean(2*gamma.*Cov_THs./Var_F);' ...
'scale_E_Hs = sqmean(2*L*Cov_EHs./Var_F);' ...
];
% ----------------------------------------------------------------------

%% Call plot_compsc_datasets.m
plot_compsc_datasets;
% ----------------------------------------------------------------------
