% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%% Run startup.m and DO NOT clear variables
% $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
% compsc_role_of_m.m
%
% --> plot_compsc_datasets.m <--
%
% Assessing the role of soil moisture variability and mean state
% in controlling the surface temperature variability 
% ( with metric gamma^2 Var(T)/Var(F) )
%
% 1) Corr(E,m) in gamma^2 Var(T)/Var(F) - chi space
% 2) Corr(E,m) in gamma^2 Var(T)/Var(F) - mbar space
% 3) Corr(E,m) in gamma^2 Var(T)/Var(F) - L*chi*sig_P space
% 4) Corr(E,m) in gamma^2 Var(T)/Var(F) - lambda space
%
% ======================================================================

%% options for both outputs
out_format = 'both';
opt_frame_col = 0;
opt_overlay = 0;
cvec = [-1:0.2:1]; 
units = '[-]';
opt_x_cvec = 'none';
color_handle = @color_corr;
% ----------------------------------------------------------------------

%% output 1)
name_add = 'chi_scale_gammaT';
vars_req = {'chi','scale_gammaT','Cor_Em'};
comp_cmd = [ ...
'gamma = [];' ...
'Var_F = sig_F.^2;' ...
'Var_T = sig_T.^2;' ...
'[j1,Cor_Em] = corr_inst(EE,mm,sig_E,sig_m);' ...
'tm_param_full;' ...
'chi = sqmean(chi);' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
];
%plot_compsc_datasets;
% ----------------------------------------------------------------------

%% output 2)
name_add = 'mbar_scale_gammaT';
vars_req = {'mbar','scale_gammaT','Cor_Em'};
comp_cmd = [ ...
'gamma = [];' ...
'Var_F = sig_F.^2;' ...
'Var_T = sig_T.^2;' ...
'[j1,Cor_Em] = corr_inst(EE,mm,sig_E,sig_m);' ...
'tm_param_full;' ...
'mbar = sqmean(mbar);' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
];
%plot_compsc_datasets;
% ----------------------------------------------------------------------

%% output 3)
name_add = 'Lchisig_P_scale_gammaT';
vars_req = {'Lchisig_P','scale_gammaT','Cor_Em'};
comp_cmd = [ ...
'gamma = [];' ...
'Var_F = sig_F.^2;' ...
'Var_T = sig_T.^2;' ...
'[j1,Cor_Em] = corr_inst(EE,mm,sig_E,sig_m);' ...
'tm_param_full;' ...
'Lchisig_P = sqmean(L*chi.*sig_P);' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
];
%plot_compsc_datasets;
% ----------------------------------------------------------------------

%% output 4)
name_add = 'lambda_scale_gammaT';
vars_req = {'lambda','scale_gammaT','Cor_Em'};
comp_cmd = [ ...
'gamma = [];' ...
'Var_F = sig_F.^2;' ...
'Var_T = sig_T.^2;' ...
'[j1,Cor_Em] = corr_inst(EE,mm,sig_E,sig_m);' ...
'tm_param_full;' ...
'lambda = sqmean(lambda);' ...
'scale_gammaT = sqmean(gamma.^2.*Var_T./Var_F);' ...
];
plot_compsc_datasets;
% ----------------------------------------------------------------------
